// examples/react/router/paraglide/src/main.tsx
import { RouterProvider } from "@tanstack/react-router";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { createRouter } from "./router";
import "./styles.css";

const router = createRouter();

const rootElement = document.getElementById("root");

if (rootElement && !rootElement.innerHTML) {
	const root = createRoot(rootElement);
	root.render(
		<StrictMode>
			<RouterProvider router={router} />
		</StrictMode>,
	);
}

// examples/solid/router/paraglide/src/main.tsx
import { RouterProvider } from "@tanstack/solid-router";
import { render } from "solid-js/web";
import { createRouter } from "./router";
import "./styles.css";

const router = createRouter();

const rootElement = document.getElementById("root");

if (rootElement) {
  render(() => <RouterProvider router={router} />, rootElement);
}
